package dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table XHAMSTER_GALLERY.
 */
public class XhamsterGallery {

    private Long id;
    private String title;
    private String galleryName;
    private String galleryUrl;
    private String sideUrl;
    private String userName;
    private String userURL;
    private String viewCount;
    private String thumbSmallUrl;
    private String thumbBigUrl;
    private Integer commentCount;
    private Integer pictureCount;
    private String addedTime;
    private String likes;
    private String dislikes;
    private String rating;
    private String category1;
    private String category2;
    private String category3;
    private String category4;
    private String category5;
    private long xhamsterUserId;

    public String getPictureUrl() {
        return pictureUrl;
    }

    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl;
    }

    private String pictureUrl;

    public XhamsterGallery() {
    }

    public XhamsterGallery(Long id) {
        this.id = id;
    }

    public XhamsterGallery(Long id, String title, String galleryName, String galleryUrl, String sideUrl, String userName, String userURL, String viewCount, String thumbSmallUrl, String thumbBigUrl, Integer commentCount, Integer pictureCount, String addedTime, String likes, String dislikes, String rating, String category1, String category2, String category3, String category4, String category5, long xhamsterUserId) {
        this.id = id;
        this.title = title;
        this.galleryName = galleryName;
        this.galleryUrl = galleryUrl;
        this.sideUrl = sideUrl;
        this.userName = userName;
        this.userURL = userURL;
        this.viewCount = viewCount;
        this.thumbSmallUrl = thumbSmallUrl;
        this.thumbBigUrl = thumbBigUrl;
        this.commentCount = commentCount;
        this.pictureCount = pictureCount;
        this.addedTime = addedTime;
        this.likes = likes;
        this.dislikes = dislikes;
        this.rating = rating;
        this.category1 = category1;
        this.category2 = category2;
        this.category3 = category3;
        this.category4 = category4;
        this.category5 = category5;
        this.xhamsterUserId = xhamsterUserId;
    }

    public XhamsterGallery(int id2) {
    	this.id = Long.valueOf(id2);
	}

	public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getGalleryName() {
        return galleryName;
    }

    public void setGalleryName(String galleryName) {
        this.galleryName = galleryName;
    }

    public String getGalleryUrl() {
        return galleryUrl;
    }

    public void setGalleryUrl(String galleryUrl) {
        this.galleryUrl = galleryUrl;
    }

    public String getSideUrl() {
        return sideUrl;
    }

    public void setSideUrl(String sideUrl) {
        this.sideUrl = sideUrl;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserURL() {
        return userURL;
    }

    public void setUserURL(String userURL) {
        this.userURL = userURL;
    }

    public String getViewCount() {
        return viewCount;
    }

    public void setViewCount(String viewCount) {
        this.viewCount = viewCount;
    }

    public String getThumbSmallUrl() {
        return thumbSmallUrl;
    }

    public void setThumbSmallUrl(String thumbSmallUrl) {
        this.thumbSmallUrl = thumbSmallUrl;
    }

    public String getThumbBigUrl() {
        return thumbBigUrl;
    }

    public void setThumbBigUrl(String thumbBigUrl) {
        this.thumbBigUrl = thumbBigUrl;
    }

    public Integer getCommentCount() {
        return commentCount;
    }

    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    public Integer getPictureCount() {
        return pictureCount;
    }

    public void setPictureCount(Integer pictureCount) {
        this.pictureCount = pictureCount;
    }

    public String getAddedTime() {
        return addedTime;
    }

    public void setAddedTime(String addedTime) {
        this.addedTime = addedTime;
    }

    public String getLikes() {
        return likes;
    }

    public void setLikes(String likes) {
        this.likes = likes;
    }

    public String getDislikes() {
        return dislikes;
    }

    public void setDislikes(String dislikes) {
        this.dislikes = dislikes;
    }

    public String getRating() {
        return rating;
    }

    public void setRating(String rating) {
        this.rating = rating;
    }

    public String getCategory1() {
        return category1;
    }

    public void setCategory1(String category1) {
        this.category1 = category1;
    }

    public String getCategory2() {
        return category2;
    }

    public void setCategory2(String category2) {
        this.category2 = category2;
    }

    public String getCategory3() {
        return category3;
    }

    public void setCategory3(String category3) {
        this.category3 = category3;
    }

    public String getCategory4() {
        return category4;
    }

    public void setCategory4(String category4) {
        this.category4 = category4;
    }

    public String getCategory5() {
        return category5;
    }

    public void setCategory5(String category5) {
        this.category5 = category5;
    }

    public long getXhamsterUserId() {
        return xhamsterUserId;
    }

    public void setXhamsterUserId(long xhamsterUserId) {
        this.xhamsterUserId = xhamsterUserId;
    }

}
