package dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table XHAMSTER_COMMENT.
 */
public class XhamsterComment {

    private Long id;
    private String userName;
    private String userUrl;
    private String thumbUrl;
    private String text;
    private String postedtime;
    private String replylink;
    private String usergender;
    private String usernationality;
    private String messagelink;

    public XhamsterComment() {
    }

    public XhamsterComment(Long id) {
        this.id = id;
    }

    public XhamsterComment(Long id, String userName, String userUrl, String thumbUrl, String text, String postedtime, String replylink, String usergender, String usernationality, String messagelink) {
        this.id = id;
        this.userName = userName;
        this.userUrl = userUrl;
        this.thumbUrl = thumbUrl;
        this.text = text;
        this.postedtime = postedtime;
        this.replylink = replylink;
        this.usergender = usergender;
        this.usernationality = usernationality;
        this.messagelink = messagelink;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserUrl() {
        return userUrl;
    }

    public void setUserUrl(String userUrl) {
        this.userUrl = userUrl;
    }

    public String getThumbUrl() {
        return thumbUrl;
    }

    public void setThumbUrl(String thumbUrl) {
        this.thumbUrl = thumbUrl;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getPostedtime() {
        return postedtime;
    }

    public void setPostedtime(String postedtime) {
        this.postedtime = postedtime;
    }

    public String getReplylink() {
        return replylink;
    }

    public void setReplylink(String replylink) {
        this.replylink = replylink;
    }

    public String getUsergender() {
        return usergender;
    }

    public void setUsergender(String usergender) {
        this.usergender = usergender;
    }

    public String getUsernationality() {
        return usernationality;
    }

    public void setUsernationality(String usernationality) {
        this.usernationality = usernationality;
    }

    public String getMessagelink() {
        return messagelink;
    }

    public void setMessagelink(String messagelink) {
        this.messagelink = messagelink;
    }

}
