package dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table XHAMSTER_VIDEO.
 */
public class XhamsterVideo {

    private Long id;
    private String title;
    private String siteUrl;
    private String streamUrl;
    private String description;
    private String userName;
    private String userURL;
    private String Runtime;
    private String viewCount;
    private String thumbUrl;
    private Integer commentCount;
    private String addedTime;
    private String likes;
    private String dislikes;
    private String rating;
    private String category1;
    private String category2;
    private String category3;
    private String category4;
    private String category5;
    private long xhamsterUserId;
    private String spriteUrl;

    public XhamsterVideo() {    	
    }

    public XhamsterVideo(Long id) {
        this.id = id;      
    }

    public XhamsterVideo(Long id, String title, String siteUrl, String streamUrl, String description, String userName, String userURL, String Runtime, String viewCount, String thumbUrl, Integer commentCount, String addedTime, String likes, String dislikes, String rating, String category1, String category2, String category3, String category4, String category5, long xhamsterUserId) {
        this.id = id;
        this.title = title;
        this.siteUrl = siteUrl;
        this.streamUrl = streamUrl;
        this.description = description;
        this.userName = userName;
        this.userURL = userURL;
        this.Runtime = Runtime;
        this.viewCount = viewCount;
        this.thumbUrl = thumbUrl;
        this.commentCount = commentCount;
        this.addedTime = addedTime;
        this.likes = likes;
        this.dislikes = dislikes;
        this.rating = rating;
        this.category1 = category1;
        this.category2 = category2;
        this.category3 = category3;
        this.category4 = category4;
        this.category5 = category5;
        this.xhamsterUserId = xhamsterUserId;      
    }

   

	public String getSpriteUrl() {
		return spriteUrl;
	}

	public void setSpriteUrl(String spriteUrl) {
		this.spriteUrl = spriteUrl;
	}

	public XhamsterVideo(int id2) {
    	this.id = Long.valueOf(id2);
		// TODO Auto-generated constructor stub
	}

	public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSiteUrl() {
        return siteUrl;
    }

    public void setSiteUrl(String siteUrl) {
        this.siteUrl = siteUrl;
    }

    public String getStreamUrl() {
        return streamUrl;
    }

    public void setStreamUrl(String streamUrl) {
        this.streamUrl = streamUrl;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserURL() {
        return userURL;
    }

    public void setUserURL(String userURL) {
        this.userURL = userURL;
    }

    public String getRuntime() {
        return Runtime;
    }

    public void setRuntime(String Runtime) {
        this.Runtime = Runtime;
    }

    public String getViewCount() {
        return viewCount;
    }

    public void setViewCount(String viewCount) {
        this.viewCount = viewCount;
    }

    public String getThumbUrl() {
        return thumbUrl;
    }

    public void setThumbUrl(String thumbUrl) {
        this.thumbUrl = thumbUrl;
    }

    public Integer getCommentCount() {
        return commentCount;
    }

    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    public String getAddedTime() {
        return addedTime;
    }

    public void setAddedTime(String addedTime) {
        this.addedTime = addedTime;
    }

    public String getLikes() {
        return likes;
    }

    public void setLikes(String likes) {
        this.likes = likes;
    }

    public String getDislikes() {
        return dislikes;
    }

    public void setDislikes(String dislikes) {
        this.dislikes = dislikes;
    }

    public String getRating() {
        return rating;
    }

    public void setRating(String rating) {
        this.rating = rating;
    }

    public String getCategory1() {
        return category1;
    }

    public void setCategory1(String category1) {
        this.category1 = category1;
    }

    public String getCategory2() {
        return category2;
    }

    public void setCategory2(String category2) {
        this.category2 = category2;
    }

    public String getCategory3() {
        return category3;
    }

    public void setCategory3(String category3) {
        this.category3 = category3;
    }

    public String getCategory4() {
        return category4;
    }

    public void setCategory4(String category4) {
        this.category4 = category4;
    }

    public String getCategory5() {
        return category5;
    }

    public void setCategory5(String category5) {
        this.category5 = category5;
    }

    public long getXhamsterUserId() {
        return xhamsterUserId;
    }

    public void setXhamsterUserId(long xhamsterUserId) {
        this.xhamsterUserId = xhamsterUserId;
    }

}
